### PR TITLE
Magnus-based methods, RF reference frame, and block splitting 

### LINKED ISSUE #201: Change RF interpretation to linear interpolation
In the current state of the code, the RFs use a zero-order-hold interpolation, which must be changed to a linear interpolation instead.

The idea is that the waveforms of both RFs and Grads must have the same kind of interpretarion.

This issue should address the problem of #200 and it is related with #167.

### LINKED ISSUE #204: BlochDict simulation method not working with multiple threads
When performing a simulation with the `BlochDict` method and with multiple threads, the REPL throws an error. Here is a MWE

```sh
julia> using KomaMRI
julia> seq = read_seq(joinpath(dirname(dirname(pathof(KomaMRI))), "examples", "1.sequences", "epi_se.seq"))
julia> obj = brain_phantom2D()
julia> sys = Scanner()
julia> simParams = KomaMRICore.default_sim_params()
julia> simParams["Nthreads"] = 2
julia> simParams["sim_method"] = KomaMRICore.BlochDict()
julia> simulate(obj, seq, sys; simParams)
ERROR: DimensionMismatch: array could not be broadcast to match destination
Stacktrace:
...
```
<details>
    <summary>Full Stack Trace</summary>

```julia
┌ Info: Running simulation in the GPU (NVIDIA GeForce GTX 1650)
│   koma_version = v"0.7.5"
│   sim_method = BlochDict(save_Mz=false)
│   spins = 6506
│   time_points = 11079
└   adc_points = 10201
ERROR: DimensionMismatch: array could not be broadcast to match destination
Stacktrace:
  [1] check_broadcast_shape
    @ .\broadcast.jl:553 [inlined]
  [2] check_broadcast_shape
    @ .\broadcast.jl:554 [inlined]
  [3] check_broadcast_axes
    @ .\broadcast.jl:556 [inlined]
  [4] instantiate
    @ .\broadcast.jl:297 [inlined]
  [5] materialize!
    @ C:\Users\beorostica\.julia\packages\GPUArrays\5XhED\src\host\broadcast.jl:41 [inlined]
  [6] materialize!(dest::SubArray{ComplexF32, 2, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Int64, Int64}, false}, bc::Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Nothing, typeof(identity), Tuple{LinearAlgebra.Transpose{ComplexF32, CUDA.CuArray{ComplexF32, 2, CUDA.Mem.DeviceBuffer}}}})
    @ Base.Broadcast .\broadcast.jl:881
  [7] run_spin_precession!(p::Phantom{Float32}, seq::KomaMRICore.DiscreteSequence{Float32}, sig::SubArray{ComplexF32, 3, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64}, false}, M::Mag{Float32}, sim_method::BlochDict)
    @ KomaMRICore C:\Users\beorostica\.julia\packages\KomaMRICore\COLVZ\src\simulation\Bloch\BlochDictSimulationMethod.jl:60
  [8] (::KomaMRICore.var"#171#173"{Phantom{Float32}, KomaMRICore.DiscreteSequence{Float32}, SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Mag{Float32}, BlochDict, Vector{Colon}})(::Tuple{Int64, UnitRange{Int64}})
    @ KomaMRICore C:\Users\beorostica\.julia\packages\KomaMRICore\COLVZ\src\simulation\SimulatorCore.jl:49
  [9] next
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\library.jl:54 [inlined]
 [10] next
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\core.jl:787 [inlined]
 [11] macro expansion
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\core.jl:181 [inlined]
 [12] __foldl__(rf::Transducers.Reduction{Transducers.NoComplete, Transducers.Reduction{Transducers.Map{KomaMRICore.var"#171#173"{Phantom{Float32}, KomaMRICore.DiscreteSequence{Float32}, SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Mag{Float32}, BlochDict, Vector{Colon}}}, Transducers.BottomRF{Transducers.Completing{typeof(ThreadsX.Implementations.return_nothing)}}}}, init::Nothing, coll::Base.Iterators.Enumerate{SubArray{UnitRange{Int64}, 1, Vector{UnitRange{Int64}}, Tuple{UnitRange{Int64}}, true}})
    @ Transducers C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\processes.jl:157
 [13] foldl_basecase
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\processes.jl:365 [inlined]
 [14] _reduce_basecase(rf::Transducers.Reduction{Transducers.Map{KomaMRICore.var"#171#173"{Phantom{Float32}, KomaMRICore.DiscreteSequence{Float32}, SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Mag{Float32}, BlochDict, Vector{Colon}}}, Transducers.BottomRF{Transducers.Completing{typeof(ThreadsX.Implementations.return_nothing)}}}, init::Nothing, reducible::Transducers.SizedReducible{Base.Iterators.Enumerate{SubArray{UnitRange{Int64}, 1, Vector{UnitRange{Int64}}, Tuple{UnitRange{Int64}}, true}}, Int64})
    @ Transducers C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\threading_utils.jl:58
 [15] _reduce(ctx::Transducers.CancellableDACContext, rf::Transducers.Reduction{Transducers.Map{KomaMRICore.var"#171#173"{Phantom{Float32}, KomaMRICore.DiscreteSequence{Float32}, SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Mag{Float32}, BlochDict, Vector{Colon}}}, Transducers.BottomRF{Transducers.Completing{typeof(ThreadsX.Implementations.return_nothing)}}}, init::Nothing, reducible::Transducers.SizedReducible{Base.Iterators.Enumerate{SubArray{UnitRange{Int64}, 1, Vector{UnitRange{Int64}}, Tuple{UnitRange{Int64}}, true}}, Int64})
    @ Transducers C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\reduce.jl:150
 [16] _reduce(ctx::Transducers.CancellableDACContext, rf::Transducers.Reduction{Transducers.Map{KomaMRICore.var"#171#173"{Phantom{Float32}, KomaMRICore.DiscreteSequence{Float32}, SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Mag{Float32}, BlochDict, Vector{Colon}}}, Transducers.BottomRF{Transducers.Completing{typeof(ThreadsX.Implementations.return_nothing)}}}, init::Nothing, reducible::Transducers.SizedReducible{Base.Iterators.Enumerate{Vector{UnitRange{Int64}}}, Int64})
    @ Transducers C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\reduce.jl:159
 [17] _transduce_assoc_nocomplete
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\reduce.jl:139 [inlined]
 [18] #transduce_assoc#177
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\reduce.jl:108 [inlined]
 [19] transduce_assoc
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\reduce.jl:84 [inlined]
 [20] #foldxt#185
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\reduce.jl:246 [inlined]
 [21] foldxt
    @ C:\Users\beorostica\.julia\packages\Transducers\yTXrD\src\reduce.jl:246 [inlined]
 [22] foreach(f::KomaMRICore.var"#171#173"{Phantom{Float32}, KomaMRICore.DiscreteSequence{Float32}, SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Mag{Float32}, BlochDict, Vector{Colon}}, itr::Base.Iterators.Enumerate{Vector{UnitRange{Int64}}}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ ThreadsX.Implementations C:\Users\beorostica\.julia\packages\ThreadsX\vXfYv\src\foreach.jl:118
 [23] foreach(f::KomaMRICore.var"#171#173"{Phantom{Float32}, KomaMRICore.DiscreteSequence{Float32}, SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Mag{Float32}, BlochDict, Vector{Colon}}, itr::Base.Iterators.Enumerate{Vector{UnitRange{Int64}}})
    @ ThreadsX.Implementations C:\Users\beorostica\.julia\packages\ThreadsX\vXfYv\src\foreach.jl:118
 [24] run_spin_precession_parallel!(obj::Phantom{Float32}, seq::KomaMRICore.DiscreteSequence{Float32}, sig::SubArray{ComplexF32, 4, CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}}, false}, Xt::Mag{Float32}, sim_method::BlochDict; Nthreads::Int64)
    @ KomaMRICore C:\Users\beorostica\.julia\packages\KomaMRICore\COLVZ\src\simulation\SimulatorCore.jl:48
 [25] run_sim_time_iter!(obj::Phantom{Float32}, seq::KomaMRICore.DiscreteSequence{Float32}, sig::CUDA.CuArray{ComplexF32, 4, CUDA.Mem.DeviceBuffer}, Xt::Mag{Float32}, sim_method::BlochDict; Nblocks::Int64, Nthreads::Int64, parts::Vector{UnitRange{Int64}}, excitation_bool::Vector{Bool}, w::Nothing)
    @ KomaMRICore C:\Users\beorostica\.julia\packages\KomaMRICore\COLVZ\src\simulation\SimulatorCore.jl:132
 [26] macro expansion
    @ .\timing.jl:501 [inlined]
 [27] simulate(obj::Phantom{Float64}, seq::Sequence, sys::Scanner; simParams::Dict{String, Any}, w::Nothing)
    @ KomaMRICore C:\Users\beorostica\.julia\packages\KomaMRICore\COLVZ\src\simulation\SimulatorCore.jl:213
 [28] top-level scope
    @ REPL[63]:1
 [29] top-level scope
    @ C:\Users\beorostica\.julia\packages\CUDA\BbliS\src\initialization.jl:52
```
</details>

The problem doesn't happen if we use just 1 thread.

It is a dimension mismatch error, so probably we need to pay attention in extreme points when performing the simulation with this method.

### LINKED ISSUE #583: Troubles at beginning of blocks in simulations
### What happened?

Hi, 

I'm using `BlochDict` to create dictionaries of signals for MRF sequences. 

Signals look fine when I look at the magnitude. Yet, checking the real and imaginary parts, I observe unwanted peaks in the signal evolutions. 

Attached are some figures showing the desired signal (1 block) and the signal obtained with 10, 20, 100 and 130 blocks. 
The peaks are regularly spaced along the sequence and the number of them seems to be the number of blocks `sim_params["Nblocks"]`, at least when this number divides the number of pulses of the sequence (260), which indicates that the bug might be depending on the type of the first event of the block (for 100 blocks, only a few peaks are observed ...). 

Is it a known bug or do you have any guess what could be the problem? I'm also attaching the notebook and pulseq sequence if necessary. 

Image

Image

Image

Image

Image

[Koma_bug_Nblocks.zip](https://github.com/user-attachments/files/21015477/Koma_bug_Nblocks.zip)

### Environment

```Markdown
OS x86_64-linux-gnu
Julia 1.11.5
KomaMRIPlots 0.9.1
KomaMRIFiles 0.9.1
KomaMRI 0.9.1
KomaMRICore 0.9.1
KomaMRIBase 0.9.1
```

### LINKED ISSUE #657: bSSFP signal is dependent on isochromats' position along the z axis even after having applied RF.freq_offset
### What happened?

Hello, 

I am simulating a bSSFP sequence used for Magnetic Resonance Fingerprinting. The issue I encounter occurs whenever I try to simulate the entire 5-slice acquisition, i.e. when I set a slice offset along z; naturally, I apply the corresponding frequency offset to the RF pulses (RF.freq_offset = Gz.amplitude * slice_position, with slice_position in meters)

The issue manifests itself as a frequency offset (df) of the bSSFP signal whenever the slice is not centered at z=0: df = (2 pi * RF_duration * Gz_amplitude * dz_offset) / (2 pi * TR). A simple example of this is shown in the Julia notebook ('DebuggingNotebook') attached and in the attached images: the signal for an isochromat at 0.01mm with RF centered at 0.01mm is different from the signal for an isochromat at 0mm with RF centered at 0mm. The signals at 0mm and 0.01 match almost perfectly for a spin at 0 Hz and a spin at 8.6Hz (calculated using the formula above for 1.6ms, 5000Hz/mm RF and TR=9ms; red and green lines on the 1st image). Even more curiously, the issue goes away when I remove the slice-select rephasers (which solves the problem, but only for a single spin whereas I'd like to simulate the slice profile).
More details on how the sequence was generated can be found in the 'SimpleSincTests' python notebook)

Any and all help would be greatly appreciated, please do let me know if there is some convention that I am not aware of. I have talked to a colleague of mine and he was just as confused as I was; we do not see the same frequency shift depending on the z position in our in vivo acquisitions which are well described by the signal simulated for z=0mm. Thank you in advance!

Best regards,
Dan

[bSSFP_sequences.zip](https://github.com/user-attachments/files/23926817/bSSFP_sequences.zip)

[DebuggingNotebook.ipynb](https://github.com/user-attachments/files/23903771/DebuggingNotebook.ipynb)

[SimpleSincTests.ipynb](https://github.com/user-attachments/files/23904301/SimpleSincTests.ipynb)

Image

Image

### Environment

```Markdown
OS x86_64-linux-gnu
Julia 1.11.6
KomaMRIPlots 0.9.4
KomaMRIFiles 0.9.3
KomaMRI 0.9.2
KomaMRICore 0.9.3
KomaMRIBase 0.9.3
```

### PR DESCRIPTION
**Pull request by cncastillo**
Fixes #583, instead of using `sim_params["Nblocks"]` (removed) a new variable `sim_params["max_block_length"]` is used to better control block size. 

Before, if you had a block with 11 time points and wanted to devide it into 3 blocks you would get:

```julia
1:4, 5:8, 9:11
```

Now you define `max_block_length = 5` and get:

```julia
1:5, 6:10, 11:11
``` 

Maximixing per-block GPU usage. 

This block-size limit should only be relevant for precession blocks. If you want to split RF blocks (more kernel calls), use `sim_params["max_rf_block_length"]`.

Another change is that the precense of an RF now is done by `abs.(seqd.B1) > 0.0` instead of a very small number, like `1e-9`.

- [x] Update CPU-based methods
	- [x] BlochCPU
	- [x] BlochSimple
	- [x] BlochDict
- [x] Update GPU-based methods
	- [x] BlochGPU
	- [x] BlochSimple
	- [x] BlochDict

---
As the fix of this bug was related to some issues with time-stepping, I also implemented a new experimental Magnus-based method that takes advantage of having the information of the current and next time point.

Right now, this is only compatible with CPU-based simulations, and there are some issues that need to be fixed.

If you want to try this PR:

# Install this PR
```julia
pkg> add https://github.com/JuliaHealth/KomaMRI.jl:KomaMRIBase#fix-sim-block-issue
pkg> add https://github.com/JuliaHealth/KomaMRI.jl:KomaMRICore#fix-sim-block-issue
pkg> add KomaMRI
```

### CODE REVIEW

File: KomaMRICore/src/simulation/SimMethods/BlochSimple/BlochSimple.jl [hunk 1]
```diff
@@ -91,15 +97,19 @@ function run_spin_excitation!(
...
-        M.z .= M.z .* exp.(-s.Δt ./ p.T1) .+ p.ρ .* (1 .- exp.(-s.Δt ./ p.T1))
+        @. M.xy = M.xy * exp(-s.Δt / p.T2)
+        @. M.z  = M.z * exp(-s.Δt / p.T1) + p.ρ * (1 - exp(-s.Δt / p.T1))
         #Reset Spin-State (Magnetization). Only for FlowPath
-        outflow_spin_reset!(M, s.t, p.motion; replace_by=p.ρ)
+        outflow_spin_reset!(M, s.tnew, p.motion; replace_by=p.ρ)
+        #Acquire signal
+        # TODO: use sim_method and sys to modify sig 
+        if s.ADC # ADC at the end of the time step
+            sig[sample] = sum(M.xy)
```
Comment (mcgrathcm) [inline KomaMRICore/src/simulation/SimMethods/BlochSimple/BlochSimple.jl]: This throws an error due to scalar indexing when run on CUDA.

Comment (cncastillo) [reply KomaMRICore/src/simulation/SimMethods/BlochSimple/BlochSimple.jl]: Solved in [9afeaee](https://github.com/JuliaHealth/KomaMRI.jl/pull/612/commits/9afeaee9b719e59c6e8fa6711272573ee7bdbe7b)
